# Generated by Django 5.2.3 on 2025-07-03 23:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahandler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='delivery_method',
            field=models.CharField(default='NEEDS DEFINED', max_length=128),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
