# Generated by Django 5.1.11 on 2025-07-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahandler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='id',
        ),
        migrations.AddField(
            model_name='client',
            name='auto_increment_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
