# Generated by Django 5.2.3 on 2025-07-04 00:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahandler', '0002_medicine_delivery_method_alter_medicine_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2025, 7, 3, 20, 3, 28, 549017), editable=False),
        ),
    ]
