# Generated by Django 5.2.3 on 2025-07-04 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahandler', '0003_medicine_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2025, 7, 4, 10, 13, 48, 699416), editable=False),
        ),
    ]
