# Generated by Django 5.2.3 on 2025-07-04 19:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahandler', '0004_alter_medicine_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2025, 7, 4, 15, 57, 41, 406595), editable=False),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='delivery_method',
            field=models.CharField(default='', max_length=128),
        ),
    ]
