# Generated by Django 5.2.3 on 2025-07-04 19:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahandler', '0005_alter_medicine_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2025, 7, 4, 15, 59, 33, 569815), editable=False),
        ),
    ]
