# Generated by Django 5.2.3 on 2025-07-05 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahandler', '0008_alter_medicine_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('medication', models.CharField(max_length=100)),
                ('doctor_name', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=50)),
                ('quantity', models.PositiveBigIntegerField()),
                ('fulfillment', models.BooleanField(default=False)),
                ('date_prescribed', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='medicine',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2025, 7, 5, 10, 50, 43, 68676), editable=False),
        ),
    ]
