# Generated by Django 5.2.3 on 2025-07-19 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahandler', '0009_prescription_alter_medicine_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2025, 7, 19, 13, 33, 14, 247492), editable=False),
        ),
    ]
