# Generated by Django 5.1.11 on 2025-07-17 19:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahandler', '0009_prescription_alter_medicine_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=100)),
                ('client_phone_number', models.CharField(max_length=10)),
                ('client_email', models.CharField(max_length=40)),
                ('client_address', models.CharField(max_length=50)),
                ('client_zip', models.CharField(max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='medicine',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='delivery_method',
            field=models.CharField(choices=[('CAP', 'Capsule'), ('LIQ', 'Liquid'), ('PIL', 'Pill'), ('INJ', 'Injection'), ('SKN', 'Transdermal'), ('INH', 'Inhalation')], default='Pill', max_length=3),
        ),
    ]
